### ISSUE TITLE
class-changes in standardize_parameters() when not refit

### ISSUE THREAD

**Issue by strengejacke** [easystats/effectsize#129]
the related code is here: https://github.com/easystats/effectsize/blob/784f4c7d896213e8dc5efb9dda93165320e91d1c/R/standardize_parameters.R#L172

this overwrites the class attribute set here:
https://github.com/easystats/effectsize/blob/784f4c7d896213e8dc5efb9dda93165320e91d1c/R/standardize_parameters.R#L350

which leads to missing CI / SE in `model_parameters()` when `standardize` is any option but `"refit"`. I _think_ I solved this in _parameters_, but if there are any issues, we might need to revert the old "behaviour" and preserve the class attribute.

**Comment by mattansb** [comment]
Ah crap, I missed that.
Can you write-up a test? What exactly broke?

**Comment by mattansb** [comment]
This back and forth between effectsize and parameters needs to be simplified...

**Comment by strengejacke** [comment]
The tests that broke were these ones:
https://github.com/easystats/parameters/blob/master/tests/testthat/test-model_parameters_std.R

However, due to the long check-time, we run quite some tests only locally, which are of course not detected by the reverse-dependency checks, so that's why this was missed. We would have needed to test _parameters_ locally on the _effectsize_ package version to be submitted, in order to detect this...

The reason for the two classes was: we could directly compute the SE from the refit-method, because we have a new model-object on the standardized data. For "posthoc", we calculated SE "manually" and added it as attribute, because it was originally not part of the returned data frame.

So in `model_parameters()`, when method was "refit", I just called `model <- effectsize::standardize(model, verbose = FALSE)` to get the new model object, while for other standardize-methods, I used this code:

https://github.com/easystats/parameters/blob/451549b0a3d6b86e0f0f551d10c623cebf3760c5/R/extract_parameters.R#L70-L86

However, this submit should fix the issue as well and work with both class-attributes:
https://github.com/easystats/parameters/blob/451549b0a3d6b86e0f0f551d10c623cebf3760c5/R/standard_error.R#L115-L139

**Comment by mattansb** [comment]
I see.

I re-wrote `standardize_parameters` - simplified it from over 250 lines to 85 lines. This new version takes care of the CI on the `effectsize` side, so no need for a `ci()` method (which we only added to avoid infinite looping between the packages) - you can get any CI columns directly from `standardize_parameters()` (but also still has a `standard_error` attribute). So this:

https://github.com/easystats/parameters/blob/451549b0a3d6b86e0f0f551d10c623cebf3760c5/R/extract_parameters.R#L70-L86

would need to change to use the returned ci columns instead of using the `ci()` method.

---

This version passes all the tests on `effectsize`. Can you see if it passes on the `parameters` side as well? And if not, what is missing?

**Comment by strengejacke** [comment]
I think due to the cyclic dependencies, we need to have this update in _effectsize_ on CRAN before it works for _parameters_. However, the other method also works, so I would change this after the next release-cycle.

**Comment by strengejacke** [comment]
Local checks for _parameters_ are ok, checks on GitHub CI as well.
