### ISSUE TITLE
Tag  "posthoc" / "smart" as *experimental*

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#139]
Following discussion here: https://github.com/easystats/effectsize/issues/6

@DominiqueMakowski 
If I'm reading the docs right, this 👆 is what "posthoc" does, "smart" seems to do something different...

So for "posthoc", I'm not sure it is possible to always perfectly emulate "refit" because for interactions and transformations you would need to recover the actual parameters, whose *meaning* (not just values) are different. If you have `exp(x)` you can just divide by `exp(sd(x))` or `sd(exp(x))` to get the same parameter as "refit".

For interactions it is more possible (which currently does work with "posthoc"), because you *can* estimate the main effect from the model (this is what `emmeans` does).

**Needed action**:
- [x] When "posthoc" / "smart" are used with transformed variables, revert to "basic" with warning suggesting "refit".
  - [x]  Document this behavior 
- [x] Document "posthoc" / "smart" as *experimental*
- Continued work on "posthoc" / "smart" by @DominiqueMakowski (:

**Comment by DominiqueMakowski** [comment]
Ah yes sorry my bad this was the "posthoc" method that I was referring to indeed 🙊 "smart" refers to our previous discussion about the standardized standardized params (i.e., with the goal of expressing them all on the same scale)

**Comment by DominiqueMakowski** [comment]
> I'm not sure it is possible to always perfectly emulate "refit" 

Yes I'm not sure either that was it's indeed exploratory (and that's why we should implement a given treatment, for instance, 2-way interaction between one continuous and one factor, only if it works in all cases and emulates "refit", otherwise leave to what "basic" would do). So that "posthoc" is, best case scenario, "refit", and worst case scenario "basic". 

I understand that you think the "basic" method is fundamentally different than "refit" and that it has its own value in the cases where it disagrees with refit, but aside from the value that its computation is straightforward, I think it's meaningless for complex parameters and that it is not what users usually want (even if they don't know it's what they want, I believe most users expect deep inside standardized parameters to the ones that would be returned by "refit"). And because of the propensity to use std. parameters as indices of effect size (and interpret them as is), the basic method can lead to disastrous results in that regards. So if there's anyway of obtaining the "refit"-like (i.e., for me, the "true" standardized parameters) without having to refit the models that'd be a fantastic advance IMO.

And yeah, the "smart" method is a separate issue of harmonizing the interpretability of these values

**Comment by mattansb** [comment]
As mentioned elsewhere, "basic" has 2 things going for it: 1) super easy, 2) gives the same results as other software (e.g., SPSS), which I think *is* important for cross-platform-consistency.
But I don't think "basic" is automatically better, and I agree that for complex designs (even simple moderation models) "refit" is better suited for what users want to know - and so I also agree that "posthoc" should be an option, and I invite you to keep working on both "posthoc" and "smart" 😁

---

What I changed is that if there are formula transformations, "posthoc" / "smart" are dropped in favor of "basic". This is a *broad* fix - it should definitely be more specific so that specific parameters should revert to the "basic" option, and not the whole thing. But that feels like more than I can do right now, so... feel free to keep working on that as well 😅

**Comment by DominiqueMakowski** [comment]
\**adds it on his todo list*\*

![](https://media.giphy.com/media/B7o99rIuystY4/giphy.gif)
