### ISSUE TITLE
separately documenting each function

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#20]
Congrats on CRAN acceptance! :)

One thought I had:
Typically, I explore the available functions in a new package using `manual.pdf` index. But while searching for `eta_` and `omega_` functions in `effectsize`, I couldn't find them. If I hadn't known better, I'd have thought that no such functions exist in this package. So I think it'd be better not to have the same `.Rd` files for similar functions; this way all functions appear in the index.

![image](https://user-images.githubusercontent.com/11330453/68946818-2dac5d80-07b4-11ea-80da-79d7318c4727.png)

**Comment by DominiqueMakowski** [comment]
Hum that's a good point. Originally (in my first pkg psycho) I had every function separated, but that was quite tough to maintain (and prone to errors). I've noticed that originally (in the sjworld) Daniel had a tendency to group a lot, so that the documentation almost looks like a small overview of a topic (for instance, "stuff to help you with Bayesian analyses). We actually never formally discussed the organization of the documentation in easystats.

I think that it's a tradeoff between maintainability and redundancy, as some of the text applies to multiple functions. A game-changer might be the new roxygen version, which allows if I'm not mistaking for (besides markdown support 🎉) for arbitrary sections of text that can be easily duplicated. (I mean I think I've seen something like that on twitter, might be mistaken). 

Thus it might be easier to have like theorethical sections copied from function to function (but located only in one place). 

Also, we should use more of the @seealso section which I realised is underused in the easyverse

**Comment by mattansb** [comment]
Perhaps we can have the help `@name` set to the topic? Will give a more human-friendly topic page...

I will look into this...

**Comment by mattansb** [comment]
@IndrajeetPatil is this still relevant? (Or: any idea how to actually do this?)

**Comment by IndrajeetPatil** [comment]
I think the current index is much better! It alludes to every important function we have. 
And, anyways, unfortunately, we don't have much control over how the manuals are generated, so this is the best we can do. Hopefully, people look at the website instead which does also list aliases, etc., in the index. 

![image](https://user-images.githubusercontent.com/11330453/101614772-a3ade300-3a0d-11eb-9010-d3b2f5dbb63d.png)
