### ISSUE TITLE
Newbie contributions?

### ISSUE THREAD

**Issue by n-a-clarke** [easystats/effectsize#26]
_"I'd like to help, but I don't know where to start"

You can look around the issue section to find some features / ideas / bugs to start working on. You can also open a new issue just to say that you're there, interested in helping out. We might have some ideas adapted to your skills._

I've been using some of your excellent packages for analysis of my PhD thesis data and would love to help out - thank you and really great job :) If there are any suggestions that fit within my current workload/skillset, I'm keen to get involved...

**Comment by DominiqueMakowski** [comment]
Hi @n-a-clarke, we'd be delighted to have your help ☺️ 

A good start is, for instance, to start getting familiar with the packages and their structure and with the github workflow. In order to do that, I'd suggest 1) **watching** the easystats package to get notified of the discussions (and try to understand what we are discussing etc.) 2) get familiar with the package structure by cloning them on your computer and exploring their structure, were functions are located, how documentation is written, where vignettes are, how testing is done etc. 3) you will likely encounter some minor things to fix, some documentation to improve, some typos to fix. This might be the occasion to get comfortable with the Github workflow by making your first small pull requests to fix some typos or add some things etc.

Then, there are plenty of things that we really need help with:

- Testing: increase the test coverage of the packages. This can be a very good exercice to understand the code in the functions, as you need to imagine edge cases and ways of testing them.
- Documentation: So many things would deserve better documentation and examples. For instance here, in effectsize, we could add more information about the different indices of effect size etc. This is good if you need to improve your theorethical knowledge of a given topic. For instance, let's say you plan to work with Factor analysis. You could go the factor analysis-related functions and add information as you learn it yourself.
- Communication: One of the most fundamental aspects of a package is its ease of use, which is achieved through tutorials. In R, this is done through vignettes and blogposts. And we really need help to write and improve existing vignettes (for instance, `performance` has none 😢), and effectsize could also use better ones. Also, writing shorter posts designed at showcasing a particular function is a very good way to learn yourself about the function and help back other users and it's a scientifically well-recognized contribution. In general, contributing is a very good way both to improve one's R skills, but also to directly participate in the open-science movement 😉 

And do let us know if you have any doubts or questions!
