### ISSUE TITLE
rethinking the CI formatting across `easystats`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/effectsize#280]
I always find it better to absorb the information if the CIs for the estimate are right next to it, and not separated by any other column in between (like `CI` here). 

```r
library(effectsize)

# output contains ci width in `CI` column
as.data.frame(cohens_d(sleep$extra, sleep$group, ci = 0.99))
#>     Cohens_d   CI    CI_low   CI_high
#> 1 -0.8321811 0.99 -2.027956 0.3826775
```

I know that the `print` method avoids this issue, but it would be nice to avoid it also in the dataframe.

**Comment by mattansb** [comment]
@IndrajeetPatil @DominiqueMakowski @strengejacke 
Let's settle this once and for all:
1. Is `CI` (level) a column, or attribute
  - if attribute, is it `ci` or `CI`?
  - if column, does it come before or after ci_low / ci_high?
2. Is the value an fraction (0.95) or not (95)?

**Comment by IndrajeetPatil** [comment]
> 1. Is `CI` (level) a `column`, or `attribute`
I would vote for being explicit about this by including it as a `column`. 
If we still want to retain as an attribute, no strong opinion about that since the users won't usually be exposed to them anyway.

>  - if attribute, is it `ci` or `CI`?
Doesn't matter to me, as long as we are consistent. 

>  - if column, does it come before or after ci_low / ci_high?
I would argue **after**, because I find it more intuitive to read CIs when they are right next to the coefficient/estimate.
But I am not too adamant about this being the case either. 
 
> 2. Is the value a fraction (0.95) or not (95)?
I would vote for it being a fraction when in a dataframe and an integer for `print` method.
Most of the time we are thinking about in terms of a fraction because that's what majority of the modeling functions expect (with some prominent exceptions like `metafor::rma` notwithstanding).

**Comment by strengejacke** [comment]
We definitely need a `CI`column, because we use it as split-criterion when multiple CIs are provided (https://easystats.github.io/see/articles/bayestestR.html#highest-density-interval-hdi-). According to being a fraction or not: this is a historical thing, because @DominiqueMakowski used to have "95" instead of ".95", even in the arguments. I think the related discussion is this one: https://github.com/easystats/bayestestR/issues/168

I'm OK with either, but we should be aware that changing this might break stuff.

**Comment by IndrajeetPatil** [comment]
> I'm OK with either, but we should be aware that changing this might break stuff.

Not a lot though, no? 
Since the `CI` column was absent from most `easystats` package outputs, except `effectsize`, there shouldn't actually be anyone who is using this as a feature.

**Comment by strengejacke** [comment]
I mean internally.

**Comment by DominiqueMakowski** [comment]
> Is CI (level) a column, or attribute

CI as a column is most of the time a bit heavy and redundant, but is indeed necessary in the case of multiple CIs. In any case, the ci arg should be stored as an attribute, as it's always good to trace the arguments passed as attributes as our structure heavily relies on autonomous postprocessing.

> if attribute, is it ci or CI?

`ci` is alright, as it is the name of the argument in the first place, so it's internally consistent.

- if column, does it come before or after ci_low / ci_high?

Mmh I'd say before? So that it's an "indicator" that explains the values that comes after? It follows the verbal logic of "The *95*% CI is *[x; y]*"

- Is the value a fraction (0.95) or not (95)?

I think regarding 95 vs. 0.95, we settled it for the latter, which made more mathematical sense. I think for legacy reason it's still 95 in some places, which is also more tidy and neat to print, but... better to be consistent I think (and I was initially in favour of 95 but the arguments for .95 were valid imo 😁)

**Comment by strengejacke** [comment]
I think _insight_ is prepared now:

``` r
x <- data.frame(
  CI = .8,
  CI_low = 2.43,
  CI_high = 5.453,
  test_CI = .9,
  test_CI_low = .1,
  test_CI_high = 1.3
)
insight::format_table(x)
#>         80% CI  test 90% CI
#> 1 [2.43, 5.45] [0.10, 1.30]

x <- data.frame(
  CI_low = 2.43,
  CI_high = 5.453,
  test_CI_low = .1,
  test_CI_high = 1.3
)
attr(x, "ci") <- .8
attr(x, "ci_test") <- .9
insight::format_table(x)
#>         80% CI  test 90% CI
#> 1 [2.43, 5.45] [0.10, 1.30]
```

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Okay, so the majority opinion and backwards compatibility concerns seem to suggest that `effectsize` should be changing its output from fraction CI (`0.95`) to integer CI (`95`).

**Comment by mattansb** [comment]
I think understood that the only change needed is to also add the ci as an attribute...

Also, I agreed with Dom about the column order here.

**Comment by DominiqueMakowski** [comment]
> suggest that effectsize should be changing its output from fraction CI (0.95) to integer CI (95).

didn't we went for fraction CI in the end?

**Comment by mattansb** [comment]
Yup...

**Comment by IndrajeetPatil** [comment]
My bad! 

Okay, then, everybody but @mattansb needs to get back to work and convert CI columns to fractions! 😄

**Comment by mattansb** [comment]
lol they already are 🥲

**Comment by DominiqueMakowski** [comment]
0.1.0 will be such a relief for everybody once we stop breaking stuff every odd day ^^

**Comment by IndrajeetPatil** [comment]
> 0.1.0 will be such a relief for everybody once we stop breaking stuff every odd day ^^

I think we are slowly getting there!

**Comment by mattansb** [comment]
closed (https://github.com/easystats/effectsize/commit/07de1488ec6bd2bc4d318b4817d9b02bd60772b8)
