### ISSUE TITLE
oddsratio to d in the context of logistic models gives different results?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/effectsize#289]
Here are 4 ways of analyzing a difference, and computing *d*:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.6.3

data <- bayestestR::simulate_difference()

ggplot(data, aes(y=V1, x=V0)) +
  geom_jitter(width=0.1) +
  see::theme_modern()
```

![](https://i.imgur.com/H6vP9xD.png)

``` r


# t-Test
x <- t.test(V1 ~ V0, data=data)
effectsize::cohens_d(V1 ~ V0, data=data)$Cohens_d
#> [1] -0.531671

# Correlation
x <- cor.test(data$V1, as.numeric(data$V0))
effectsize::r_to_d(x$estimate)
#>       cor 
#> 0.5370688

# Linear model
x <- lm(V1 ~ V0, data=data)
effectsize::t_to_d(insight::get_statistic(x)[2, 2], insight::get_df(x))$d
#> [1] 0.5370688

# Logistic model
x <- glm(V0 ~ V1, data=data, family="binomial")
effectsize::oddsratio_to_d(insight::get_parameters(x)[2, 2], log=TRUE)
#> [1] 0.3150333
```

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

They all give fairly similar results but the one from the logistic model, is that normal? Is that improve-able?

**Comment by mattansb** [comment]
Dom, I can't tell if you're trolling me.....

**Comment by DominiqueMakowski** [comment]
I know we already established that it was completely different hahah but STILL it bothers me that we don't fall back on the same value as we are trying to quantify essentially an equivalent quantity 😁  can ya explain again like Im your kiddo 😅

**Comment by mattansb** [comment]
Okay, so imagine you want to see if boys have more Lego pieces compared to girls.
You would do this with a t-test and your effect size would be Cohen's d:

``` r
Legos <- bayestestR::simulate_difference(n = 1e4, names = c("gender", "Legos"))

effectsize::cohens_d(Legos ~ gender, data = Legos)
#> Cohen's d |         95% CI
#> --------------------------
#> -0.50     | [-0.54, -0.46]
#> 
#> - Estimated using pooled SD.
```

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

But oh no! Your silly dad didn't write down how many toys each kids has, he only wrote if they have a lot or a little!
(adults talk: the continuous variable was dichotomized somehow)

How would you do this?
You would now predict "a lot / a little" from gender in a logistic regression (or really in a 2*2 xtab in this simple example).
But you still would like to know the difference between boys and girls in the amount of Legos - luckily you can approximate this from the log(OR)!
(adult talk: you want to approximate the difference on the continuous scale, using only the dichotomized data!)

``` r
Legos <- within(Legos, {
  Legos_d <- factor(Legos < median(Legos), labels = c(":(", ":)"))
})

m <- glm(Legos_d ~ gender, data = Legos, family = binomial())
effectsize::oddsratio_to_d(coef(m)[2], log = TRUE)
#>    gender1 
#> -0.4415787

OR <- effectsize::oddsratio(Legos$gender, Legos$Legos_d)
effectsize::oddsratio_to_d(OR$Odds_ratio, log = FALSE)
#> [1] -0.4415787
```

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This is pretty close to the true Cohen's d! (it is smaller, because there is some data-loss, but it is a good enough approximation)

Yay!

###  ***FIN***

---

- What `oddsratio_to_d()` is: approximate `d(y_continuous  ~ g)` from `OR(y_dichotomized ~ g)`
- What `oddsratio_to_d()` isn't: approximate `d(y_continuous  ~ g)` from `OR(g ~ y_continuous)`

**Comment by mattansb** [comment]
Your silence is deafening!!!!

**Comment by DominiqueMakowski** [comment]
Your exolanation is so clear it takes some time to sink in!

**Comment by DominiqueMakowski** [comment]
But is there *any* equivalence or similarity between `glm(gender ~ Legos, data = Legos, family = binomial())` and `lm(Legos ~ gender, data = Legos, family = binomial())` ? any bridge between the two?

**Comment by mattansb** [comment]
For the very simple case of a "reversed t-test", yes, they are related:

``` r
library(purrr)
library(effectsize)
library(tidyr)
library(ggplot2)

grid <- expand.grid(
  n = seq(30, 200, by = 20),
  d = seq(0, 1.5, by = 0.1)
)

safe_OR <- safely(
  ~coef(glm(V0 ~ scale(V1), data = .x, family = binomial())),
  otherwise = NA
)

get_OR <- function(n, d) {
  data <- bayestestR::simulate_difference(n, d)
  
  OR_d <- oddsratio(data$V0, data$V1 > mean(data$V1), 
                    ci = NULL, log = TRUE)[[1]]
  OR_d <- oddsratio_to_d(OR_d, log = TRUE)
  
  OR_c <- safe_OR(data)[[1]][2]
  
  data.frame("actual conversion" = OR_d, "reverse t-test" = OR_c)
}

logOR <- map2_dfr(grid$n, grid$d, get_OR)

cbind(grid, logOR) %>% 
  pivot_longer(c(actual.conversion,reverse.t.test)) %>%
  ggplot(aes(d, value, color = n)) +
  facet_wrap(~name, scales = "free") +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)
```

![](https://i.imgur.com/BoP9VNd.png)

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

But 
1. Not linearly (looks exponential)
1. They aren't **analogous** - which is the beauty of the original conversion.
2. For more complex designs, this "reverse t test" would break.

**Comment by DominiqueMakowski** [comment]
fascinating 😅 thanks for the walkthrough

**Comment by mattansb** [comment]
![](https://i.imgur.com/AFD4sK6.gif)
