### ISSUE TITLE
Validate SE formulas for the rank biserial correlation

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#336]
#322

**Comment by bwiernik** [comment]
Yeah, so I actually think there are some errors in these formulas (https://github.com/jasp-stats/jasp-desktop/blob/a45e080ba8d1afeb051867604c904e0ea5ed2b8e/JASP-Engine/JASP/R/ttestindependentsamples.R#L295)

So, they compute a rank-biserial correlation (labelled `d` in their code) as:

```r
stat <- as.numeric(r$statistic)
m    <- as.numeric(r$estimate)
rankBis    <- abs(as.numeric(1-(2*stat)/(ns[1]*ns[2]))) * sign(m)
```

Then, they start out with the [normal approximation SE for U](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Normal_approximation_and_tie_correction): `wSE <- sqrt((ns[1]*ns[2] * (ns[1]+ns[2] + 1))/12)`

The delta method transform for `wSE` to become `rankBisSE` is: `rankBisSE<- sqrt(4 * 1/(ns[1]*ns[2])^2 * wSE^2)`

So that right so far. 

But then, they Fisher z (atanh) transform r_rbs to z and use `rankBisSE` to construct normal CI around z before back-transforming. That shouldn't be correct. 

The delta method tranform for `atanh(x)` is `transSE <- sqrt( xSE^2 * (1 / (1 - x^2)^2))`.

So the final SE for the non-paired rank-biserial Z should be `zSE <- sqrt(rankBisSE^2 / (1 - rankBis^2)^2)`.

For a Pearson correlation, this division is what enables Fisher's z to not depend on the population correlation value (variance of pearson R ≈ (1 - r^2)^2 / (n - 3), so variance of Z = 1 / (n - 3). But for a rank-biserial, it would seem that this division sticks around? It would have a fairly small effect for r < .3, but starts to have a big widening effect after that. 

@mattansb Could you perhaps compare bootstrap SE for the Z values to the analytic SEs computed as follows:

`sqrt((n1 + n2 + 1) / (3 * n1 * n2))` # current, simplified

`sqrt((n1 + n2 + 1) / (3 * n1 * n2) / (1 - r_rbs^2)^2 )` # what the delta method says it should be…

**Comment by bwiernik** [comment]
(Same situation with wilcoxon)

**Comment by mattansb** [comment]
How's this?

``` r
library(effectsize)

sim_rRBS_SE <- function(seed, n = 30, B = 1000) {
  set.seed(seed)
  g <- sample(1:2, size = n, replace = TRUE)
  y <- rnorm(n, mean = g, sd = 1)
  g <- factor(g)
  n1 <- sum(g == "1")
  n2 <- n - n1
  
  (r <- rank_biserial(y, g, ci = NULL)[[1]])
  
  # Some functions
  SE1 <- function(n1, n2) sqrt((n1 + n2 + 1) / (3 * n1 * n2)) # current
  SE2 <- function(n1, n2, r_rbs) SE1(n1, n2) / sqrt((1 - r_rbs^2)^2 ) # should be
  sample_2_samples <- function(y, g) {
    split(y, g) <- lapply(split(y, g), 
                          sample, replace = TRUE)
    y
  }
  
  
  # Run sim
  z_boot <- numeric(B)
  
  for (b in seq_len(B)) {
    y_boot <- sample_2_samples(y, g)
    r_boot <- rank_biserial(y_boot, g, ci = NULL)[[1]]
    z_boot[b] <- atanh(r_boot)  
  }
  
  
  # Results
  c(
    boot = sd(z_boot),
    old = SE1(n1, n2),
    new = SE2(n1, n2, r)
  )
}

sim_rRBS_SE(2)
#>      boot       old       new 
#> 0.2752713 0.2147812 0.3344773
sim_rRBS_SE(3, n = 35)
#>      boot       old       new 
#> 0.2486083 0.2048366 0.2646890
sim_rRBS_SE(5, n = 100)
#>      boot       old       new 
#> 0.1615665 0.1161389 0.2106745
sim_rRBS_SE(7, n = 57)
#>      boot       old       new 
#> 0.1863560 0.1562395 0.2493674
```

<sup>Created on 2021-05-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


The "old" def seems to be too small... What do you think?

**Comment by mattansb** [comment]
How's this?

``` r
library(effectsize)

sim_rRBS_SE <- function(seed, n = 30, B = 1000) {
  set.seed(seed)
  g <- sample(1:2, size = n, replace = TRUE)
  y <- rnorm(n, mean = g, sd = 1)
  g <- factor(g)
  n1 <- sum(g == "1")
  n2 <- n - n1
  
  (r <- rank_biserial(y, g, ci = NULL)[[1]])
  
  # Some functions
  SE1 <- function(n1, n2) sqrt((n1 + n2 + 1) / (3 * n1 * n2)) # current
  SE2 <- function(n1, n2, r_rbs) SE1(n1, n2) / sqrt((1 - r_rbs^2)^2 ) # should be
  sample_2_samples <- function(y, g) {
    split(y, g) <- 
      lapply(split(y, g), sample, replace = TRUE)
    y
  }
  
  
  # Run sim
  z_boot <- numeric(B)
  
  for (b in seq_len(B)) {
    y_boot <- sample_2_samples(y, g)
    r_boot <- rank_biserial(y_boot, g, ci = NULL)[[1]]
    z_boot[b] <- atanh(r_boot)  
  }
  
  
  # Results
  c(
    boot = sd(z_boot),
    old = SE1(n1, n2),
    new = SE2(n1, n2, r)
  )
}

sim_rRBS_SE(2)
#>      boot       old       new 
#> 0.2752713 0.2147812 0.3344773
sim_rRBS_SE(3, n = 35)
#>      boot       old       new 
#> 0.2486083 0.2048366 0.2646890
sim_rRBS_SE(5, n = 100)
#>      boot       old       new 
#> 0.1615665 0.1161389 0.2106745
sim_rRBS_SE(7, n = 57)
#>      boot       old       new 
#> 0.1863560 0.1562395 0.2493674
```

<sup>Created on 2021-05-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The "old" def seems to be too small... What do you think?

**Comment by bwiernik** [comment]
Thanks! 

Running with some larger sample sizes, it seems that the old SE slightly underestimates and the new SE slightly overestimates. The magnitude of the bias seems consistently smaller with the old SE formula. We see that in your tests too. 

```r
a1 <- list(sim_rRBS_SE(2, n = 100), sim_rRBS_SE(3, n = 500), sim_rRBS_SE(5, n = 1000), sim_rRBS_SE(7, n = 2000))
do.call(rbind, a1) |> transform(do = old - boot, dn = new - boot)
#         boot        old        new           do          dn
# 1 0.12495386 0.11606918 0.13804100 -0.008884672 0.013087140
# 2 0.05897859 0.05169139 0.07065913 -0.007287199 0.011680542
# 3 0.04126536 0.03653426 0.05086571 -0.004731106 0.009600346
# 4 0.02926503 0.02583876 0.03683212 -0.003426266 0.007567096
```

I changed the simulated r_rbs from -.54 to -.84 (by multiplying as.numeric(g) by 2) and got this though:

```r
      boot        old        new 
0.04086176 0.02583876 0.09070589 
```

When the r_rbs is large, the new SE can get really inflated. 

The sample dependency of the r_rbs estimate is also potentially an issue. Note that if we take the old SE and adjust it using the true population correlation (.707) rather than the sample estimate, it's very close to the bootstrapped value. 

```
0.02583876  / (1 - psychmeta:::.convert_d_to_r(2)^2)
0.05167752
```

So based on this, I think the old SE is likely to be more reliable.
