### ISSUE TITLE
Error when using effectsize::standardize_posteriors on multivariate BRMS model

### ISSUE THREAD

**Issue by NADonnelly** [easystats/effectsize#344]
Hello! I have been trying to use the bayestestR::mediate function with a multivariate BRMS model. When running the mediation, there is a warning regarding direct and indirect effects being on different scales, and it is suggested that I standardise my model using effectsize::standardize. 

However, if I run effectsize::standardize or any variants e.g. effectsize::standardize_posteriors on the multivariate BRMS model, I get an error:

Error in !info$is_linear : invalid argument type

Looking at the code for standardize_posteriors I wonder if this is occurring because insight::model_info returns different results for each part of the multivariate model.

Here is a reproducible example:

library(bayestestR)
library(brms)
library(effectsize)

#load sample data
data(jobs)

set.seed(123)

#Make a binary outcome (as the actual analysis I am planning has a binary outcome)
jobs = 
  jobs %>% 
  as_tibble() %>% 
  mutate(depress_bin = ifelse(depress2 > 2.5,1,0)) %>%
  mutate(depress_bin = factor(depress_bin))

#Fit Bayesian mediation model in brms
f1 <- bf(job_seek ~ treat + econ_hard + sex + age) + gaussian()
f2 <- bf(depress_bin ~ treat + job_seek + econ_hard + sex + age) + bernoulli()    

m1 <- brm(f1 + f2 + set_rescor(FALSE), data = jobs, cores = 4)

#This gives the suggestion to use standardize
mediation(m1)

#This generates the error
standardize_posteriors(m1)

Session Info:

R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Many thanks!

**Comment by mattansb** [comment]
@strengejacke Why does this warning pop-up? Any difference in scale should be canceled out, no? The direct and indirect effects are in y-per-x unit (the units of m cancel out)?

**Comment by mattansb** [comment]
@strengejacke It seems like for `brms` the model info is a list of model infos... How would you go about detecting this? I can't even see if `isTRUE(insight::model_info(x)$is_multivariate)` unless already knowing this :/

**Comment by strengejacke** [comment]
You can use [`insight::is_multivariate()`](https://easystats.github.io/insight/reference/is_multivariate.html) first.
The warning is due to the fact that mediator and treatment are on different scales (one linear and one logistic regression), so the "proportion mediated", which is calculated from the estimates, is probably biased - I think. But I'm not 100% sure about that, I thought I read it somewhere, but cannot recall. @bwiernik any experience with mediation analysis?

**Comment by mattansb** [comment]
``` r
m11 <- lm(mpg ~ hp + disp, data = mtcars)
m12 <- lm(hp ~ disp, data = mtcars)

mediation::mediate(m12, m11, boot = FALSE,
                   treat = "disp", mediator = "hp") |>
  summary()
#> 
#> Causal Mediation Analysis 
#> 
#> Quasi-Bayesian Confidence Intervals
#> 
#>                Estimate 95% CI Lower 95% CI Upper p-value    
#> ACME           -0.01117     -0.02369         0.00   0.056 .  
#> ADE            -0.03014     -0.04486        -0.02  <2e-16 ***
#> Total Effect   -0.04130     -0.05062        -0.03  <2e-16 ***
#> Prop. Mediated  0.27067     -0.00394         0.56   0.056 .  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Sample Size Used: 32 
#> 
#> 
#> Simulations: 1000




mtcars <- mtcars |>
  transform(hp100 = hp*100)

m21 <- lm(mpg ~ hp100 + disp, data = mtcars)
m22 <- lm(hp100 ~ disp, data = mtcars)

mediation::mediate(m22, m21, boot = FALSE,
                   treat = "disp", mediator = "hp100") |>
  summary()
#> 
#> Causal Mediation Analysis 
#> 
#> Quasi-Bayesian Confidence Intervals
#> 
#>                Estimate 95% CI Lower 95% CI Upper p-value    
#> ACME            -0.0111      -0.0243         0.00   0.078 .  
#> ADE             -0.0303      -0.0443        -0.02  <2e-16 ***
#> Total Effect    -0.0413      -0.0505        -0.03  <2e-16 ***
#> Prop. Mediated   0.2657      -0.0329         0.59   0.078 .  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Sample Size Used: 32 
#> 
#> 
#> Simulations: 1000
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Ah, mediation analysis--the name of statistical inference. 

I haven't dug into the code here, but a general note, we should only report the "proportion mediated" statistic if the signs of all of the paths in the mediation are the same. This statistic really only makes sense for "consistent mediation". If the signs differ, the statistic can take on values larger than 1.00. 

It's not really meaningful to compute these statistics with a mix of response distributions from different families. I don't understand the suggestion to standardize the variables. That's kind of a non-sequitor here. The issue isn't variables variances, but the response distribution. 

I'm not even sure that the proportion mediated statistic itself is meaningful for binomial distributions. In logistic regression, there are inherent interactions even without multiplicative terms because of the bounded nature of the probability scale. The additive proportion mediated metric doesn't really apply because it's based on cases where such a decomposition of variance is possible. 

(Personally, I'd also prefer to drop the "causal" from the title. It's a widespread misconception that simply computing mediation statistics enables causal inference. Doing that requires extremely strong assumptions about the ignorability of both the X and M variables [that both the predictor and mediator are effectively randomly assigned], and these assumptions are very rarely justified. We might even consider adding a cautionary message to this function output.)

**Comment by strengejacke** [comment]
Just for the record, here's the vignette that compares mediation, bayestestR and lavaan: https://easystats.github.io/bayestestR/articles/mediation.html

**Comment by mattansb** [comment]
This is not easily resolved, so the current solution is to return an informative warning with some actionable advice.

```R
library(brms)
f <- brmsformula(am ~ mpg,
                 family = bernoulli()) + 
  brmsformula(mpg ~ hp, family = gaussian())

m <- brm(f, data = mtcars)

effectsize::effectsize(m)
#> Error: multivariate brmsfit models not supported.
#> As an alternative: you may standardize your data (and adjust your priors), and re-fit the model.
```
