### ISSUE TITLE
 cohens_d function returns an error when using both paired = TRUE and a formula for the x argument

### ISSUE THREAD

**Issue by pydemull** [easystats/effectsize#610]
**Describe the bug**
The `cohens_d` function (and also `hedges_g` function) returns an error when using x argument as a formula and `paired = TRUE`.

**To Reproduce**
```R
cohens_d(Sepal.Length ~ Species, data = iris[iris$Species != "virginica", ], paired = TRUE)
#> Error: cannot use 'paired = TRUE' in formula method.
```

**Expected behavior**
No error.

**Specifiations:**
 - `R` Version [4.3.1]
 - `effectsize` Version [0.8.6]

**Comment by mattansb** [comment]
This is expected, and is consistent with the upcoming changes in `R>=4.4.0` where this method will not be supported in `t.test()`. See https://github.com/r-devel/r-svn/pull/142.

If you wish to use the formula method for a paired test/effect size, you will now need to use the `Pair()` function like so:

``` r
library(effectsize)

t.test(Pair(Sepal.Length[Species=="setosa"], Sepal.Length[Species=="versicolor"]) ~ 1,
       data = iris)
#> 
#>  Paired t-test
#> 
#> data:  Pair(Sepal.Length[Species == "setosa"], Sepal.Length[Species == "versicolor"])
#> t = -10.146, df = 49, p-value = 1.242e-13
#> alternative hypothesis: true mean difference is not equal to 0
#> 95 percent confidence interval:
#>  -1.114203 -0.745797
#> sample estimates:
#> mean difference 
#>           -0.93

cohens_d(Pair(Sepal.Length[Species=="setosa"], Sepal.Length[Species=="versicolor"]) ~ 1,
         data = iris)
#> Cohen's d |         95% CI
#> --------------------------
#> -1.43     | [-1.83, -1.03]
```

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


(This is not a good example, since the data in `iris` is not paired. See the example in `cohens_d()` for an example with actual paired data.)

**Comment by pydemull** [comment]
Thanks a lot for your quick answer. My apologies for the example, I will be more carefull about that the next time. Best
