### ISSUE TITLE
Moving functions around

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#92]
I think:

- `adjust()` is better suited in `correlation` (the only place it is used)
- `format_standardize()` is better suited in `modelbased` (the only place it is used) or `insight` (with the other "format" functions).
- Also, maybe the `interpret()` family is better off in `report` (the only place it is used), as it covers not only interpertation of effect sizes but also p-value, various Bayesian measures, etc.

What do you think?

**Comment by strengejacke** [comment]
Afaik, @DominiqueMakowski recently moved all `interpret()` functions to effectsize... 😄

**Comment by DominiqueMakowski** [comment]
- move adjust: Why not, although the main reason why it's here is because its part of the "data" transformation functions like standardize, normalize, ranktransform etc.
- move format_standardize: why not, don't have a strong opinion for this one, it's just that it also made sense to keep it close to standardize ^^
- interpret: meh, for practical reasons and theoretical reasons it might be good to dissociate. Practical because 1) report is not yet fully operational 2) because report is already a conundrum so I move it here as this is a "closed" and stable feature that can be outsourced to here where it also makes more sense regarding the documentation etc. And theoretical reasons 'cause interpret() essentially implements published guidelines in an "objective" manner, in the sense that the interpretation of one effect size given a set of rules of thumb is like an "objective" piece of information. And essentially it'd be good if report didn't make any computations or hard work, simply focusing of combining the pieces that are given to it. Not sure I successfully made myself clear here, but for this one I think it makes sense to keep it here, despite the fact that "interpretation guidelines" are often criticized by experts (yet used by tons of people). Again, it's also easier to have that feature here and be able to discuss limitations and alternatives, than having it lost in the coding nightmare that I made of report 😁

**Comment by mattansb** [comment]
Ah, I see... 

In that case, I suggest waiting for report to be fully operational, at which point we can move there functions there (:

**Comment by DominiqueMakowski** [comment]
That means that correlation must be cranned before effectsize

**Comment by mattansb** [comment]
I'm leaving these functions in effectsize for now - will need to investigate inter-function dependencies and such. 🤷‍♂️

**Comment by strengejacke** [comment]
> format_standardize() is better suited in modelbased (the only place it is used) or insight (with the other "format" functions).

Might be an option. I'm starting moving the `format_*()` functions from _parameters_ to _insight_, because I realize more of them are required in other packages as well, that do not depend on _parameters_. I still re-export them in _parameters_ to not break code, until the complete refactoring is done.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #340, which is the new avatar of this issue.
